### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by camswims2** [Cin316/X-Schedule#3]
Not sure if this is the right place for this, but I was wondering if it would be possible to add a text entry box to each class, that way we can enter homework. On some days (like X days), i dont have math for example, and then i would have to open up my homework app and X Schedule to see if i need to do the homework for the next day. If its not too difficult a homework entry box for each class would be great, thanks.

**Comment by Cin316** [comment]
This is the right place for issues!  Thanks for using it! @camswims2

Could you elaborate on what you mean?

Homework tracking is beyond the scope of X Schedule.  Dedicated homework planners and to-do lists have many more features that I wouldn't be able to implement into X Schedule.  I'd rather encourage people to use a really good, separate homework app than use X Schedule.  Any homework planning features I try to write into X Schedule would not be able to match a dedicated app.  If there was some way to integrate my schedule into other homework apps, I would be willing to do that.  I might add an option to export classes into the iOS Calendar app, for example.  All in all, I'd rather not X Schedule into a homework tracker.

**Comment by Jonathanplas** [comment]
The ability to export classes into the iOS Calendar app sounds extremely useful.

**Comment by Cin316** [comment]
@Panzhuangzhuang @camswims2 I will definitely look into adding this for the next version.
