### ISSUE TITLE
Feature Request - Event and start time only

### ISSUE THREAD

**Issue by ericbrass** [Cin316/X-Schedule#4]
Please add in the ability to add in a "class" with just the class name and start time only, no end time.

**Comment by Cin316** [comment]
Now that I've adapted the `Schedule` object system to allow for different types of `ScheduleItem`s, I've started adding `ScheduleItem`s for classes with only a start time and classes with no times.  See commit 7db39f7.

**Comment by Cin316** [comment]
Caching and loading `ScheduleItem`s with 2 times, 2 times (with 1 missing), 1 time, and no times all seems to be working.

![screen shot 2017-05-21 at 9 15 04 pm](https://cloud.githubusercontent.com/assets/1988780/26289109/eba53e9e-3e6a-11e7-926c-4d83a0c388c5.png)

Each type of `ScheduleItem` starts with the `blockName` and ends with a `timeToken`.  The structure of the `timeToken` defines how the `ScheduleItem` will be parsed.  Do not put spaces within the `timeToken`.

`ScheduleItem` Class Name | Description | `timeToken` Text Encoding | Appearance | Notes
--- | --- | --- | --- | ---
`TimeSpanScheduleItem` | Two times (start and end) | `11:00-11:10` | 11:00 - 11:10 | This is the only `ScheduleItem` that will work correctly with highlighting.
`TimeSpanScheduleItem` | One time (no start) | `-9:55` or `?:??-9:55` | ?:?? - 9:55 | 
`TimeSpanScheduleItem` | One time (no end) | `9:00-` or `9:00-?:??` | 9:00 - ?:?? | 
`TimePointScheduleItem` | Just one time | `12:00` | 12:00 | 
`DescriptionScheduleItem` | No times | ` ` (No time token) |  | Use this for a `ScheduleItem` that does not have an associated time, but should still show up in the schedule.

**Comment by Cin316** [comment]
This feature has been added and released in the latest update.

**Comment by ericbrass** [comment]
YO NICK.

It's Mr. Brass - I don't have your contact information now that you're moving beyond St. X.  If you don't mind, could you shoot me an email at ebrass@stxavier.org with a way to get ahold of you?

Also... just some food for thought...  since you're no longer a student here, have you considered asking for some type of payment from St. X to continue using X-Schedule?  Personally I think it's only fair.  Just a suggestion.

Thanks,
Mr. B.
